# Generated by Django 5.2 on 2025-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='user_phone_number_idx'),
        ),
    ]
