# Generated by Django 5.2 on 2025-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['slug'], name='categories_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['slug'], name='products_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='products_category_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['discount'], name='products_discount_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['price'], name='products_price_idx'),
        ),
    ]
