# Generated by Django 5.2.5 on 2025-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories_categories_slug_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Дополнительные изображения'),
        ),
    ]
