# Generated by Django 5.2.5 on 2025-09-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
    ]
